version: '2'
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
services:
  mariadb:
    image: mariadb:10.1
    environment:
      MARIADB_DATABASE: data_wordpress
      MARIADB_PASSWORD: wordpress_password
      MARIADB_ROOT_PASSWORD: mariadb_my_root
      MARIADB_USER: wordpress_user
    volumes:
    - mariadb_data:/data
  wordpress-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DATABASE_NAME: data_wordpress
      WORDPRESS_DATABASE_PASSWORD: wordpress_password
      WORDPRESS_DATABASE_USER: wordpress_user
      WORDPRESS_PASSWORD: Itga#2018
      WORDPRESS_USERNAME: admin
    volumes:
    - wordpress_data:/data
 