wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=ITGA#2018
    ports:
    - 3000:3000/tcp
    volumes:
     - ./code:/code
     - ./html:/var/www/html
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=<password>
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
 