.catalog:
  name: "Wordpress"
  version: "v1"
  description: "BlaBlaBla ceci est une instance de Wordpress"
  uuid: php-adminer-1

wordpress:
  scale: 1
  health_check:
    port: 80
    interval: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
    response_timeout: 2000
    request_line: 'GET "/" "HTTP/1.0"'
