.catalog:
  name: "Wordpress"
  version: "v1"
  description: "BlaBlaBla ceci est une instance de Wordpress"
  uuid: php-adminer-1

version: '2'
services:
  mariadb:
    scale: 1
    start_on_create: true
  wordpress-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: wordpress
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  wordpress:
    retain_ip: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 80
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
      request_line: GET / HTTP/1.0
